/*
 * This file is generated by jOOQ.
 */
package io.github.quickmsg.persistent.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 1L;


    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();


    public final Smqtt SMQTT = Smqtt.SMQTT;


    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        return Arrays.<Schema>asList(
            Smqtt.SMQTT);
    }
}
