/*
 * This file is generated by jOOQ.
 */
package io.github.quickmsg.persistent.tables;


import io.github.quickmsg.persistent.tables.tables.Databasechangelog;
import io.github.quickmsg.persistent.tables.tables.Databasechangeloglock;
import io.github.quickmsg.persistent.tables.tables.SmqttRetain;
import io.github.quickmsg.persistent.tables.tables.SmqttSession;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Smqtt extends SchemaImpl {

    private static final long serialVersionUID = 1L;


    public static final Smqtt SMQTT = new Smqtt();

    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;


    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;


    public final SmqttRetain SMQTT_RETAIN = SmqttRetain.SMQTT_RETAIN;


    public final SmqttSession SMQTT_SESSION = SmqttSession.SMQTT_SESSION;


    private Smqtt() {
        super("smqtt", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            SmqttRetain.SMQTT_RETAIN,
            SmqttSession.SMQTT_SESSION);
    }
}
