/*
 * This file is generated by jOOQ.
 */
package io.github.quickmsg.persistent.tables;


import io.github.quickmsg.persistent.tables.tables.MqttMsgLog;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Smqtt extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>smqtt</code>
     */
    public static final Smqtt SMQTT = new Smqtt();

    /**
     * The table <code>smqtt.mqtt_msg_log</code>.
     */
    public final MqttMsgLog MQTT_MSG_LOG = MqttMsgLog.MQTT_MSG_LOG;

    /**
     * No further instances allowed
     */
    private Smqtt() {
        super("smqtt", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            MqttMsgLog.MQTT_MSG_LOG);
    }
}
