/*
 * This file is generated by jOOQ.
 */
package io.github.quickmsg.persistent.tables;


import io.github.quickmsg.persistent.tables.tables.SmqttRetain;
import io.github.quickmsg.persistent.tables.tables.SmqttSession;


/**
 * Convenience access to all tables in smqtt.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>smqtt.smqtt_retain</code>.
     */
    public static final SmqttRetain SMQTT_RETAIN = SmqttRetain.SMQTT_RETAIN;

    /**
     * The table <code>smqtt.smqtt_session</code>.
     */
    public static final SmqttSession SMQTT_SESSION = SmqttSession.SMQTT_SESSION;
}
