/*
 * This file is generated by jOOQ.
 */
package io.github.quickmsg.persistent.tables;


import io.github.quickmsg.persistent.tables.tables.MqttMsgLog;


/**
 * Convenience access to all tables in smqtt.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>smqtt.mqtt_msg_log</code>.
     */
    public static final MqttMsgLog MQTT_MSG_LOG = MqttMsgLog.MQTT_MSG_LOG;
}
