{
 "title": "smqtt-netty",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(reactor_netty_bytebuf_allocator_heap_arenas, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Tcp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tcp Received Bytes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(reactor_netty_tcp_server_data_received_bytes_count{instance=\"$instance\"})",
     "legendFormat": "reactor_netty_tcp_server_data_received_bytes_count"
    },
    {
     "expr": "max(reactor_netty_tcp_server_data_received_bytes_max{instance=\"$instance\"})",
     "legendFormat": "reactor_netty_tcp_server_data_received_bytes_max"
    },
    {
     "expr": "sum(reactor_netty_tcp_server_data_received_bytes_sum{instance=\"$instance\"})",
     "legendFormat": "reactor_netty_tcp_server_data_received_bytes_sum"
    }
   ]
  },
  {
   "title": "Tcp Sent Bytes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(reactor_netty_tcp_server_data_sent_bytes_count{instance=\"$instance\"})",
     "legendFormat": "reactor_netty_tcp_server_data_sent_bytes_count"
    },
    {
     "expr": "sum(reactor_netty_tcp_server_data_sent_bytes_max{instance=\"$instance\"})",
     "legendFormat": "reactor_netty_tcp_server_data_sent_bytes_max"
    },
    {
     "expr": "sum(reactor_netty_tcp_server_data_sent_bytes_sum{instance=\"$instance\"})",
     "legendFormat": "reactor_netty_tcp_server_data_sent_bytes_sum"
    }
   ]
  },
  { "title": "Bytebuf监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Bytebuf分配",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(reactor_netty_bytebuf_allocator_chunk_size{instance=\"$instance\"})",
     "legendFormat": "reactor_netty_bytebuf_allocator_chunk_size"
    },
    {
     "expr": "sum(reactor_netty_bytebuf_allocator_direct_arenas{instance=\"$instance\"})",
     "legendFormat": "reactor_netty_bytebuf_allocator_direct_arenas"
    },
    {
     "expr": "sum(reactor_netty_bytebuf_allocator_heap_arenas{instance=\"$instance\"})",
     "legendFormat": "reactor_netty_bytebuf_allocator_heap_arenas"
    }
   ]
  },
  {
   "title": "Bytebuf使用",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(reactor_netty_bytebuf_allocator_used_direct_memory{instance=\"$instance\"})",
     "legendFormat": "reactor_netty_bytebuf_allocator_used_direct_memory"
    },
    {
     "expr": "sum(reactor_netty_bytebuf_allocator_used_heap_memory{instance=\"$instance\"})",
     "legendFormat": "reactor_netty_bytebuf_allocator_used_heap_memory"
    }
   ]
  },
  {
   "title": "Bytebuf缓存",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(reactor_netty_bytebuf_allocator_normal_cache_size{instance=\"$instance\"})",
     "legendFormat": "reactor_netty_bytebuf_allocator_normal_cache_size"
    },
    {
     "expr": "sum(reactor_netty_bytebuf_allocator_small_cache_size{instance=\"$instance\"})",
     "legendFormat": "reactor_netty_bytebuf_allocator_small_cache_size"
    },
    {
     "expr": "sum(reactor_netty_bytebuf_allocator_threadlocal_caches{instance=\"$instance\"})",
     "legendFormat": "reactor_netty_bytebuf_allocator_threadlocal_caches"
    }
   ]
  }
 ]
}