{
 "title": "smqtt-application",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(smqtt_connect_count, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "实时数据", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "连接计数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smqtt_connect_count{instance=\"$instance\"}",
     "legendFormat": "连接计数"
    }
   ]
  },
  {
   "title": "订阅数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "smqtt_subscribe_count{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "事件(qps)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "publish",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(smqtt_publish_event_count_total{instance=\"$instance\"}[1m])",
     "legendFormat": "publish"
    }
   ]
  },
  {
   "title": "subscribe",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(smqtt_subscribe_event_count_total{instance=\"$instance\"}[1m])",
     "legendFormat": "subscribe"
    }
   ]
  },
  {
   "title": "connect",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(smqtt_connect_event_count_total{instance=\"$instance\"}[1m])",
     "legendFormat": "连接数"
    }
   ]
  },
  {
   "title": "close",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(smqtt_close_event_count_total{instance=\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "unscribe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(smqtt_unscribe_event_count_total{instance=\"$instance\"}[1m])",
     "legendFormat": "unscribe"
    }
   ]
  },
  {
   "title": "disconnect",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(smqtt_disconnect_event_count_total{instance=\"$instance\"}[1m])",
     "legendFormat": "disconnect"
    }
   ]
  }
 ]
}